package presenters;

public enum Event {
	SHOW_ADD_PRODUCT,SHOW_UPDATE_PRODUCT,BUY,ADD_PRODUCT,
	UPDATE_PRODUCT,CHANGE_SELECTION,SHOW_DELETE_PRODUCT,DELETE_PRODUCT,SHOW_PRODUCT_LIST,
	JP_ACCESS,JP_REGISTRATION,JP_LOGIN,JP_ACCESS_MANAGER,INVENTORY,TOP5_CLIENTS,
	TOP5_PRODUCTS,JP_ACCESS_CLIENT,SALES_REPORT,SHOW_PROFILE,SHOW_UPDATE_PROFILE,
	DELETE_PROFILE,SHOW_CLIENT_LIST,UPDATE_CLIENT,SHOW_UPDATE_CLIENT,SHOW_DELETE_CLIENT,
	DELETE_CLIENT,ADD_CLIENT,SHOW_REGISTRATION, CLIENTS_REPORT, TOP5_MAX_PRICE_PRODUCT, 
	TOP5_CLIENTS_BY_REGION
}